GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/3

###
DELETE http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Dale Gordon",
    "number": "27-84-123456"
}

###